#!/bin/bash
cd /tmp/rom # Depends on where source got synced

# Normal build
source build/envsetup.sh
export SAKURA_BUILD_TYPE=gapps
export SELINUX_IGNORE_NEVERALLOWS=true
lunch lineage_merlin-userdebug
export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
ccache -M 20G
ccache -o compression=true
ccache -z

up(){
	curl bashupload.com -T $1
}

make_metalava(){
	mka api-stubs-docs -j26
	mka system-api-stubs-docs -j26
	mka test-api-stubs-docs -j26
}

make_rom(){
	make bacon -j26
	zip=$(up out/target/product/merlin/*zip)
	echo " "
	echo "$zip"
}

make_metalava && make_rom
sleep 10 && kill "$!"
