#!/bin/bash

MANIFEST=git://github.com/ProjectSakura/android.git
BRANCH=11

mkdir -p /tmp/rom
cd /tmp/rom

# Repo init command, that -device,-mips,-darwin,-notdefault part will save you more time and storage to sync, add more according to your rom and choice. Optimization is welcomed! Let's make it quit, and with depth=1 so that no unnecessary things.
repo init --no-repo-verify --depth=1 -u "$MANIFEST" -b "$BRANCH" -g default,-device,-mips,-darwin,-notdefault
git config --global user.name Box In A Box
git config --global user.email evanferrao@gmail.com

# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again with -j8
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all) || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8

#merlin stuff
git clone https://github.com/boxboi689/android_device_xiaomi_merlin.git -b eleven device/xiaomi/merlin
git clone https://github.com/Redmi-MT6768/android_kernel_xiaomi_mt6768.git -b ten kernel/xiaomi/mt6768
git clone https://github.com/Redmi-MT6768/android_vendor_xiaomi_merlin.git -b ten vendor/xiaomi/merlin
rm -rf device/mediatek/sepolicy && git clone --depth=1 --single-branch https://github.com/PixelExperience/device_mediatek_sepolicy device/mediatek/sepolicy
rm -rf vendor/mediatek/interfaces && git clone --depth=1 --single-branch https://github.com/PixelExperience/vendor_mediatek_interfaces vendor/mediatek/interfaces
rm -rf vendor/mediatek/opensource && git clone --depth=1 --single-branch https://github.com/PixelExperience/vendor_mediatek-opensource vendor/mediatek/opensource
rm -rf vendor/mediatek/ims && git clone https://github.com/Redmi-MT6768/android_vendor_mediatek_ims.git -b eleven vendor/mediatek/ims
